real:
  A: 8
  B: null
  C: null
  D: null
  E: 7
  F: null
  G: 5
  H: 10
  I: 9
  K: 4
  L: 3
  M: 2
  N: 1
  O: 0
  Q: 11
  R: 12
  S: 13
  T: 14
  U: 15
simulator:
  A: 1
  B: 5
  C: 6
  D: 7
  E: 2
  F: 3
  G: 4
  H: 8
  I: 9
  K: 15
  L: 16
  M: 17
  N: 18
  O: 19
  Q: 10
  R: 11
  S: 12
  T: 13
  U: 14
